config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root "home#index"

  resources :films, only: %i[index]
  resources :characters, only: %i[index]
  resources :locations, only: %i[index]
  resources :species, only: %i[index]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/characters_controller.rb
class CharactersController < ApplicationController  

    def index
        @client = StudioGhibliApi::Client.new
        @characters = @client.get_all_characters(limit: 48)
    end

end

app/controllers/films_controller.rb
class FilmsController < ApplicationController

    def index
        @client = StudioGhibliApi::Client.new
        @films = @client.get_all_films
    end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

    def index
    end
    
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController

    def index
        @client = StudioGhibliApi::Client.new
        @locations = @client.get_all_locations(limit: 24)
        @i = 1
    end

end

app/controllers/species_controller.rb
class SpeciesController < ApplicationController

    def index
        @client = StudioGhibliApi::Client.new
        @all_species = @client.get_all_species(limit: 6)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/characters/index.html.erb
<div class="characters">
  <header>
    <nav>
      <%= render "layouts/logo" %>
      <ul>
        <li>
          <%= link_to "Home", root_path %>
        </li>
        <li>
          <%= link_to "Films", films_path %>
        </li>
        <li class="li">
          <%= link_to "Characters", characters_path %>
        </li>
        <li>
          <%= link_to "Locations", locations_path %>
        </li>
        <li>
          <%= link_to "Species", species_index_path %>
        </li>
      </ul>
    </nav>
  </header>
  <main>
    <%= image_tag "bg.jpg" %>
    <div class="overlay">
      <div class="container">
        <% @characters.each do |character| %>
          <%= link_to "https://ghibli.fandom.com/wiki/#{character["name"]}", class: "list" do %>
            <div class="box">
              <%= image_tag character["name"] %>
              <div class="name"><%= character["name"]%></div>
            </div>
          <% end %>
        <% end %>
      </div>
    </div>
  </main>
</div>

app/views/films/index.html.erb
<div class="films">
  <header>
    <nav>
      <%= render "layouts/logo" %>
      <ul>
        <li>
          <%= link_to "Home", root_path %>
        </li>
        <li class="li">
          <%= link_to "Films", films_path %>
        </li>
        <li>
          <%= link_to "Characters", characters_path %>
        </li>
        <li>
          <%= link_to "Locations", locations_path %>
        </li>
        <li>
          <%= link_to "Species", species_index_path %>
        </li>
      </ul>
    </nav>
  </header>
  <main>
    <%= image_tag "bg.jpg" %>
    <div class="overlay">
      <div class="container">
        <% @films.each do |film| %>
          <%= link_to "https://ghibli.fandom.com/wiki/#{film["title"]}", class: "list" do %>
            <img src="<%= film["movie_banner"]%>">
            <div class="box">
              <div class="title"><%= film["title"]%></div>
            <div class="original-title"><%= film["original_title"]%> (<%= film["original_title_romanised"]%>)</div>
            <div class="release-date"><%= film["release_date"]%></div>
              
              
              <div class="description"><%= film["description"]%></div>

              
              
            </div>
          <% end %>
        <% end %>
      </div>
    </div>
  </main>
</div>

app/views/home/index.html.erb
<div class="home">
<header>
  <nav>
    <%= render "layouts/logo" %>
    <ul>
      <li class="li">
        <%= link_to "Home", root_path %>
      </li>
      <li>
        <%= link_to "Films", films_path %>
      </li>
      <li>
        <%= link_to "Characters", characters_path %>
      </li>
      <li>
        <%= link_to "Locations", locations_path %>
      </li>
      <li>
        <%= link_to "Species", species_index_path %>
      </li>
    </ul>
  </nav>
</header>
<main>
<%= image_tag "bg.jpg" %>
<div class="overlay">
  <div class="container">
    <%= render "layouts/ghibli" %>
    <div class="description">Studio Ghibli Inc. (Japanese: 株式会社スタジオジブリ, Hepburn: Kabushiki-gaisha Sutajio Jiburi) is a Japanese animation film studio headquartered in Koganei, Tokyo. It is best known for its animated feature films, and has also produced several short subjects, television commercials, and two television films. Its mascot and most recognizable symbol is a character named Totoro, a giant spirit inspired by raccoon dogs (tanuki) and cats from the 1988 anime film My Neighbor Totoro. Among the studio's highest-grossing films are Spirited Away (2001), Howl's Moving Castle (2004) and Ponyo (2008). The studio was founded on June 15, 1985, by directors Hayao Miyazaki and Isao Takahata and producer Toshio Suzuki, after the successful performance of Topcraft's Nausicaä of the Valley of the Wind (1984). It has also collaborated with video game studios on the visual development of several games.</div>
    <%= link_to "https://www.netflix.com/search?q=studio%20ghibli", class: "button" do %>
      <%= image_tag "play.png" %> Watch on Netflix
    <% end %>
  </div>
</div>
<%= video_tag "ghibli.mov", controls: false, autoplay: true, loop: :loop, muted: true, autobuffer: true, poster: false%>


</main>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Studio Ghibli</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= favicon_link_tag "favicon.png" %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/locations/index.html.erb
<div class="locations">
  <header>
    <nav>
      <%= render "layouts/logo" %>
      <ul>
        <li>
          <%= link_to "Home", root_path %>
        </li>
        <li>
          <%= link_to "Films", films_path %>
        </li>
        <li>
          <%= link_to "Characters", characters_path %>
        </li>
        <li class="li">
          <%= link_to "Locations", locations_path %>
        </li>
        <li>
          <%= link_to "Species", species_index_path %>
        </li>
      </ul>
    </nav>
  </header>
  <main>
    <%= image_tag "bg.jpg" %>
    <div class="overlay">
      <div class="container">
        <div class="box">
          <% @locations.each do |location| %>
            <div class="slider" style="--i:<%= @i += 1 %>;"><%= image_tag location["name"] %>
              <div class="details"><%= location["name"]%></div>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </main>
</div>

app/views/species/index.html.erb
<div class="species">
  <header>
    <nav>
      <%= render "layouts/logo" %>
      <ul>
        <li>
          <%= link_to "Home", root_path %>
        </li>
        <li>
          <%= link_to "Films", films_path %>
        </li>
        <li>
          <%= link_to "Characters", characters_path %>
        </li>
        <li>
          <%= link_to "Locations", locations_path %>
        </li>
        <li class="li">
          <%= link_to "Species", species_index_path %>
        </li>
      </ul>
    </nav>
  </header>
  <main>
    <%= image_tag "bg.jpg" %>
    <div class="overlay">
      <div class="container">
        <% @all_species.each do |species| %>
          <%= link_to "https://ghibli.fandom.com/wiki/#{species["name"]}", class: "list" do %>
            <%= image_tag species["name"]%>
            <div class="box">
              <div class="title"><%= species["name"]%></div>
              <span>NAME</span>
              <div class="classification"><%= species["classification"]%></div>
              <span>CLASSIFICATION</span>
            </div>
          <% end %>
        <% end %>
      </div>
    </div>
  </main>
</div>